name: {{cookiecutter.repo_name}}
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 
  envied: ^0.3.0+3
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^5.0.1

  master_utility :
    # path: packages/master_utility_flutter 
    git:
      url: https://x-access-token:glpat-zsCVmCYyPnEFKorRodz6@gitlab.webelight.co.in/webelight/master_utility_flutter.git
      ref: dev
  internet_connection_checker: ^1.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.production
    - assets/images/
    - assets/fonts/
    - assets/colors/
    - assets/lottie/
    # - assets/images/

# flutter_gen:
#   integrations:
#     flutter_svg: true



flutter_gen:
  output: lib/config/assets/ # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml