name: {{cookiecutter.repo_name}}
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # Dependency Injection
  connectivity_plus: ^4.0.2 # Internet connection check


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  build_runner: ^2.4.6 # Code generator
 

flutter:
  uses-material-design: true

  # assets:
    # - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true

